version: '3'

services:
  flightpad:
    build: .
    ports:
      - 3000:3000
    environment:
        DB_HOST: 'postgres'
        DB_PORT: 5432
        DB_USER: 'default'
        DB_PASSWORD: 'secret'
        DB_NAME: flightpad_test
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - '.docker/data/postgres:/var/lib/postgresql/data'
