version: '3'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: default
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - '.docker/data/postgres:/var/lib/postgresql/data'
    links:
      - "flightpad"
    
  flightpad:
    #image: flightpad
    container_name: flightpad
    build: .
    ports:
      - 3000:3000
    environment:
        DATABASE_URL: 'postgresql://default:secret@postgresql:5432/flightpad_test?schema=public'